name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-lint-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: services/inventory-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        working-directory: services/inventory-service
        run: flake8 src

      - name: Run tests with pytest
        working-directory: services/inventory-service
        run: pytest --junitxml=pytest-report.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.python-version }}
          path: services/inventory-service/pytest-report.xml

      - name: Build Docker image
        working-directory: services/inventory-service
        run: docker build -t inventory-service .